/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pingcap/apiserver/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTidbBackups implements TidbBackupInterface
type FakeTidbBackups struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var tidbbackupsResource = schema.GroupVersionResource{Group: "core.pingcap.com", Version: "v1alpha1", Resource: "tidbbackups"}

var tidbbackupsKind = schema.GroupVersionKind{Group: "core.pingcap.com", Version: "v1alpha1", Kind: "TidbBackup"}

// Get takes name of the tidbBackup, and returns the corresponding tidbBackup object, and an error if there is any.
func (c *FakeTidbBackups) Get(name string, options v1.GetOptions) (result *v1alpha1.TidbBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tidbbackupsResource, c.ns, name), &v1alpha1.TidbBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbBackup), err
}

// List takes label and field selectors, and returns the list of TidbBackups that match those selectors.
func (c *FakeTidbBackups) List(opts v1.ListOptions) (result *v1alpha1.TidbBackupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tidbbackupsResource, tidbbackupsKind, c.ns, opts), &v1alpha1.TidbBackupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TidbBackupList{ListMeta: obj.(*v1alpha1.TidbBackupList).ListMeta}
	for _, item := range obj.(*v1alpha1.TidbBackupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tidbBackups.
func (c *FakeTidbBackups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tidbbackupsResource, c.ns, opts))

}

// Create takes the representation of a tidbBackup and creates it.  Returns the server's representation of the tidbBackup, and an error, if there is any.
func (c *FakeTidbBackups) Create(tidbBackup *v1alpha1.TidbBackup) (result *v1alpha1.TidbBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tidbbackupsResource, c.ns, tidbBackup), &v1alpha1.TidbBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbBackup), err
}

// Update takes the representation of a tidbBackup and updates it. Returns the server's representation of the tidbBackup, and an error, if there is any.
func (c *FakeTidbBackups) Update(tidbBackup *v1alpha1.TidbBackup) (result *v1alpha1.TidbBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tidbbackupsResource, c.ns, tidbBackup), &v1alpha1.TidbBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbBackup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTidbBackups) UpdateStatus(tidbBackup *v1alpha1.TidbBackup) (*v1alpha1.TidbBackup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tidbbackupsResource, "status", c.ns, tidbBackup), &v1alpha1.TidbBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbBackup), err
}

// Delete takes name of the tidbBackup and deletes it. Returns an error if one occurs.
func (c *FakeTidbBackups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tidbbackupsResource, c.ns, name), &v1alpha1.TidbBackup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTidbBackups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tidbbackupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TidbBackupList{})
	return err
}

// Patch applies the patch and returns the patched tidbBackup.
func (c *FakeTidbBackups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TidbBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tidbbackupsResource, c.ns, name, data, subresources...), &v1alpha1.TidbBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbBackup), err
}
