/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pingcap/apiserver/pkg/apis/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTidbInstances implements TidbInstanceInterface
type FakeTidbInstances struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var tidbinstancesResource = schema.GroupVersionResource{Group: "core.pingcap.com", Version: "v1alpha1", Resource: "tidbinstances"}

var tidbinstancesKind = schema.GroupVersionKind{Group: "core.pingcap.com", Version: "v1alpha1", Kind: "TidbInstance"}

// Get takes name of the tidbInstance, and returns the corresponding tidbInstance object, and an error if there is any.
func (c *FakeTidbInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.TidbInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tidbinstancesResource, c.ns, name), &v1alpha1.TidbInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbInstance), err
}

// List takes label and field selectors, and returns the list of TidbInstances that match those selectors.
func (c *FakeTidbInstances) List(opts v1.ListOptions) (result *v1alpha1.TidbInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tidbinstancesResource, tidbinstancesKind, c.ns, opts), &v1alpha1.TidbInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TidbInstanceList{ListMeta: obj.(*v1alpha1.TidbInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha1.TidbInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tidbInstances.
func (c *FakeTidbInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tidbinstancesResource, c.ns, opts))

}

// Create takes the representation of a tidbInstance and creates it.  Returns the server's representation of the tidbInstance, and an error, if there is any.
func (c *FakeTidbInstances) Create(tidbInstance *v1alpha1.TidbInstance) (result *v1alpha1.TidbInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tidbinstancesResource, c.ns, tidbInstance), &v1alpha1.TidbInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbInstance), err
}

// Update takes the representation of a tidbInstance and updates it. Returns the server's representation of the tidbInstance, and an error, if there is any.
func (c *FakeTidbInstances) Update(tidbInstance *v1alpha1.TidbInstance) (result *v1alpha1.TidbInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tidbinstancesResource, c.ns, tidbInstance), &v1alpha1.TidbInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbInstance), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTidbInstances) UpdateStatus(tidbInstance *v1alpha1.TidbInstance) (*v1alpha1.TidbInstance, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tidbinstancesResource, "status", c.ns, tidbInstance), &v1alpha1.TidbInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbInstance), err
}

// Delete takes name of the tidbInstance and deletes it. Returns an error if one occurs.
func (c *FakeTidbInstances) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tidbinstancesResource, c.ns, name), &v1alpha1.TidbInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTidbInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tidbinstancesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TidbInstanceList{})
	return err
}

// Patch applies the patch and returns the patched tidbInstance.
func (c *FakeTidbInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TidbInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tidbinstancesResource, c.ns, name, data, subresources...), &v1alpha1.TidbInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TidbInstance), err
}
