/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package v1alpha1

import (
	"github.com/kubernetes-incubator/apiserver-builder-alpha/pkg/builders"
	"github.com/pingcap/apiserver/pkg/apis/core"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	coreTidbBackupStorage = builders.NewApiResource( // Resource status endpoint
		core.InternalTidbBackup,
		TidbBackupSchemeFns{},
		func() runtime.Object { return &TidbBackup{} },     // Register versioned resource
		func() runtime.Object { return &TidbBackupList{} }, // Register versioned resource list
		&TidbBackupStrategy{builders.StorageStrategySingleton},
	)
	coreTidbInstanceStorage = builders.NewApiResource( // Resource status endpoint
		core.InternalTidbInstance,
		TidbInstanceSchemeFns{},
		func() runtime.Object { return &TidbInstance{} },     // Register versioned resource
		func() runtime.Object { return &TidbInstanceList{} }, // Register versioned resource list
		&TidbInstanceStrategy{builders.StorageStrategySingleton},
	)
	ApiVersion = builders.NewApiVersion("core.pingcap.com", "v1alpha1").WithResources(
		coreTidbBackupStorage,
		builders.NewApiResource( // Resource status endpoint
			core.InternalTidbBackupStatus,
			TidbBackupSchemeFns{},
			func() runtime.Object { return &TidbBackup{} },     // Register versioned resource
			func() runtime.Object { return &TidbBackupList{} }, // Register versioned resource list
			&TidbBackupStatusStrategy{builders.StatusStorageStrategySingleton},
		), coreTidbInstanceStorage,
		builders.NewApiResource( // Resource status endpoint
			core.InternalTidbInstanceStatus,
			TidbInstanceSchemeFns{},
			func() runtime.Object { return &TidbInstance{} },     // Register versioned resource
			func() runtime.Object { return &TidbInstanceList{} }, // Register versioned resource list
			&TidbInstanceStatusStrategy{builders.StatusStorageStrategySingleton},
		))

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

//
// TidbBackup Functions and Structs
//
// +k8s:deepcopy-gen=false
type TidbBackupSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type TidbBackupStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type TidbBackupStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type TidbBackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TidbBackup `json:"items"`
}

//
// TidbInstance Functions and Structs
//
// +k8s:deepcopy-gen=false
type TidbInstanceSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type TidbInstanceStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type TidbInstanceStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type TidbInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TidbInstance `json:"items"`
}
