// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	core "github.com/pingcap/apiserver/pkg/apis/core"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*PdSpec)(nil), (*core.PdSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PdSpec_To_core_PdSpec(a.(*PdSpec), b.(*core.PdSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.PdSpec)(nil), (*PdSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_PdSpec_To_v1alpha1_PdSpec(a.(*core.PdSpec), b.(*PdSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbBackup)(nil), (*core.TidbBackup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbBackup_To_core_TidbBackup(a.(*TidbBackup), b.(*core.TidbBackup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbBackup)(nil), (*TidbBackup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbBackup_To_v1alpha1_TidbBackup(a.(*core.TidbBackup), b.(*TidbBackup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbBackupList)(nil), (*core.TidbBackupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbBackupList_To_core_TidbBackupList(a.(*TidbBackupList), b.(*core.TidbBackupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbBackupList)(nil), (*TidbBackupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbBackupList_To_v1alpha1_TidbBackupList(a.(*core.TidbBackupList), b.(*TidbBackupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbBackupSpec)(nil), (*core.TidbBackupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbBackupSpec_To_core_TidbBackupSpec(a.(*TidbBackupSpec), b.(*core.TidbBackupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbBackupSpec)(nil), (*TidbBackupSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbBackupSpec_To_v1alpha1_TidbBackupSpec(a.(*core.TidbBackupSpec), b.(*TidbBackupSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbBackupStatus)(nil), (*core.TidbBackupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbBackupStatus_To_core_TidbBackupStatus(a.(*TidbBackupStatus), b.(*core.TidbBackupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbBackupStatus)(nil), (*TidbBackupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbBackupStatus_To_v1alpha1_TidbBackupStatus(a.(*core.TidbBackupStatus), b.(*TidbBackupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbBackupStatusStrategy)(nil), (*core.TidbBackupStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbBackupStatusStrategy_To_core_TidbBackupStatusStrategy(a.(*TidbBackupStatusStrategy), b.(*core.TidbBackupStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbBackupStatusStrategy)(nil), (*TidbBackupStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbBackupStatusStrategy_To_v1alpha1_TidbBackupStatusStrategy(a.(*core.TidbBackupStatusStrategy), b.(*TidbBackupStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbBackupStrategy)(nil), (*core.TidbBackupStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbBackupStrategy_To_core_TidbBackupStrategy(a.(*TidbBackupStrategy), b.(*core.TidbBackupStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbBackupStrategy)(nil), (*TidbBackupStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbBackupStrategy_To_v1alpha1_TidbBackupStrategy(a.(*core.TidbBackupStrategy), b.(*TidbBackupStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbInstance)(nil), (*core.TidbInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbInstance_To_core_TidbInstance(a.(*TidbInstance), b.(*core.TidbInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbInstance)(nil), (*TidbInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbInstance_To_v1alpha1_TidbInstance(a.(*core.TidbInstance), b.(*TidbInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbInstanceList)(nil), (*core.TidbInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbInstanceList_To_core_TidbInstanceList(a.(*TidbInstanceList), b.(*core.TidbInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbInstanceList)(nil), (*TidbInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbInstanceList_To_v1alpha1_TidbInstanceList(a.(*core.TidbInstanceList), b.(*TidbInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbInstanceSpec)(nil), (*core.TidbInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbInstanceSpec_To_core_TidbInstanceSpec(a.(*TidbInstanceSpec), b.(*core.TidbInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbInstanceSpec)(nil), (*TidbInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbInstanceSpec_To_v1alpha1_TidbInstanceSpec(a.(*core.TidbInstanceSpec), b.(*TidbInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbInstanceStatus)(nil), (*core.TidbInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbInstanceStatus_To_core_TidbInstanceStatus(a.(*TidbInstanceStatus), b.(*core.TidbInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbInstanceStatus)(nil), (*TidbInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbInstanceStatus_To_v1alpha1_TidbInstanceStatus(a.(*core.TidbInstanceStatus), b.(*TidbInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbInstanceStatusStrategy)(nil), (*core.TidbInstanceStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbInstanceStatusStrategy_To_core_TidbInstanceStatusStrategy(a.(*TidbInstanceStatusStrategy), b.(*core.TidbInstanceStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbInstanceStatusStrategy)(nil), (*TidbInstanceStatusStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbInstanceStatusStrategy_To_v1alpha1_TidbInstanceStatusStrategy(a.(*core.TidbInstanceStatusStrategy), b.(*TidbInstanceStatusStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbInstanceStrategy)(nil), (*core.TidbInstanceStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbInstanceStrategy_To_core_TidbInstanceStrategy(a.(*TidbInstanceStrategy), b.(*core.TidbInstanceStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbInstanceStrategy)(nil), (*TidbInstanceStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbInstanceStrategy_To_v1alpha1_TidbInstanceStrategy(a.(*core.TidbInstanceStrategy), b.(*TidbInstanceStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TidbSpec)(nil), (*core.TidbSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TidbSpec_To_core_TidbSpec(a.(*TidbSpec), b.(*core.TidbSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TidbSpec)(nil), (*TidbSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TidbSpec_To_v1alpha1_TidbSpec(a.(*core.TidbSpec), b.(*TidbSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TikvSpec)(nil), (*core.TikvSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TikvSpec_To_core_TikvSpec(a.(*TikvSpec), b.(*core.TikvSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TikvSpec)(nil), (*TikvSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TikvSpec_To_v1alpha1_TikvSpec(a.(*core.TikvSpec), b.(*TikvSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_PdSpec_To_core_PdSpec(in *PdSpec, out *core.PdSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Image = in.Image
	out.ImagePullPolicy = (*v1.PullPolicy)(unsafe.Pointer(in.ImagePullPolicy))
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	out.Resources = in.Resources
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_v1alpha1_PdSpec_To_core_PdSpec is an autogenerated conversion function.
func Convert_v1alpha1_PdSpec_To_core_PdSpec(in *PdSpec, out *core.PdSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PdSpec_To_core_PdSpec(in, out, s)
}

func autoConvert_core_PdSpec_To_v1alpha1_PdSpec(in *core.PdSpec, out *PdSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Image = in.Image
	out.ImagePullPolicy = (*v1.PullPolicy)(unsafe.Pointer(in.ImagePullPolicy))
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	out.Resources = in.Resources
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_core_PdSpec_To_v1alpha1_PdSpec is an autogenerated conversion function.
func Convert_core_PdSpec_To_v1alpha1_PdSpec(in *core.PdSpec, out *PdSpec, s conversion.Scope) error {
	return autoConvert_core_PdSpec_To_v1alpha1_PdSpec(in, out, s)
}

func autoConvert_v1alpha1_TidbBackup_To_core_TidbBackup(in *TidbBackup, out *core.TidbBackup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TidbBackupSpec_To_core_TidbBackupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TidbBackupStatus_To_core_TidbBackupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TidbBackup_To_core_TidbBackup is an autogenerated conversion function.
func Convert_v1alpha1_TidbBackup_To_core_TidbBackup(in *TidbBackup, out *core.TidbBackup, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbBackup_To_core_TidbBackup(in, out, s)
}

func autoConvert_core_TidbBackup_To_v1alpha1_TidbBackup(in *core.TidbBackup, out *TidbBackup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_TidbBackupSpec_To_v1alpha1_TidbBackupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_TidbBackupStatus_To_v1alpha1_TidbBackupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_TidbBackup_To_v1alpha1_TidbBackup is an autogenerated conversion function.
func Convert_core_TidbBackup_To_v1alpha1_TidbBackup(in *core.TidbBackup, out *TidbBackup, s conversion.Scope) error {
	return autoConvert_core_TidbBackup_To_v1alpha1_TidbBackup(in, out, s)
}

func autoConvert_v1alpha1_TidbBackupList_To_core_TidbBackupList(in *TidbBackupList, out *core.TidbBackupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.TidbBackup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_TidbBackupList_To_core_TidbBackupList is an autogenerated conversion function.
func Convert_v1alpha1_TidbBackupList_To_core_TidbBackupList(in *TidbBackupList, out *core.TidbBackupList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbBackupList_To_core_TidbBackupList(in, out, s)
}

func autoConvert_core_TidbBackupList_To_v1alpha1_TidbBackupList(in *core.TidbBackupList, out *TidbBackupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]TidbBackup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_TidbBackupList_To_v1alpha1_TidbBackupList is an autogenerated conversion function.
func Convert_core_TidbBackupList_To_v1alpha1_TidbBackupList(in *core.TidbBackupList, out *TidbBackupList, s conversion.Scope) error {
	return autoConvert_core_TidbBackupList_To_v1alpha1_TidbBackupList(in, out, s)
}

func autoConvert_v1alpha1_TidbBackupSpec_To_core_TidbBackupSpec(in *TidbBackupSpec, out *core.TidbBackupSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_TidbBackupSpec_To_core_TidbBackupSpec is an autogenerated conversion function.
func Convert_v1alpha1_TidbBackupSpec_To_core_TidbBackupSpec(in *TidbBackupSpec, out *core.TidbBackupSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbBackupSpec_To_core_TidbBackupSpec(in, out, s)
}

func autoConvert_core_TidbBackupSpec_To_v1alpha1_TidbBackupSpec(in *core.TidbBackupSpec, out *TidbBackupSpec, s conversion.Scope) error {
	return nil
}

// Convert_core_TidbBackupSpec_To_v1alpha1_TidbBackupSpec is an autogenerated conversion function.
func Convert_core_TidbBackupSpec_To_v1alpha1_TidbBackupSpec(in *core.TidbBackupSpec, out *TidbBackupSpec, s conversion.Scope) error {
	return autoConvert_core_TidbBackupSpec_To_v1alpha1_TidbBackupSpec(in, out, s)
}

func autoConvert_v1alpha1_TidbBackupStatus_To_core_TidbBackupStatus(in *TidbBackupStatus, out *core.TidbBackupStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_TidbBackupStatus_To_core_TidbBackupStatus is an autogenerated conversion function.
func Convert_v1alpha1_TidbBackupStatus_To_core_TidbBackupStatus(in *TidbBackupStatus, out *core.TidbBackupStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbBackupStatus_To_core_TidbBackupStatus(in, out, s)
}

func autoConvert_core_TidbBackupStatus_To_v1alpha1_TidbBackupStatus(in *core.TidbBackupStatus, out *TidbBackupStatus, s conversion.Scope) error {
	return nil
}

// Convert_core_TidbBackupStatus_To_v1alpha1_TidbBackupStatus is an autogenerated conversion function.
func Convert_core_TidbBackupStatus_To_v1alpha1_TidbBackupStatus(in *core.TidbBackupStatus, out *TidbBackupStatus, s conversion.Scope) error {
	return autoConvert_core_TidbBackupStatus_To_v1alpha1_TidbBackupStatus(in, out, s)
}

func autoConvert_v1alpha1_TidbBackupStatusStrategy_To_core_TidbBackupStatusStrategy(in *TidbBackupStatusStrategy, out *core.TidbBackupStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_TidbBackupStatusStrategy_To_core_TidbBackupStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_TidbBackupStatusStrategy_To_core_TidbBackupStatusStrategy(in *TidbBackupStatusStrategy, out *core.TidbBackupStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbBackupStatusStrategy_To_core_TidbBackupStatusStrategy(in, out, s)
}

func autoConvert_core_TidbBackupStatusStrategy_To_v1alpha1_TidbBackupStatusStrategy(in *core.TidbBackupStatusStrategy, out *TidbBackupStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_core_TidbBackupStatusStrategy_To_v1alpha1_TidbBackupStatusStrategy is an autogenerated conversion function.
func Convert_core_TidbBackupStatusStrategy_To_v1alpha1_TidbBackupStatusStrategy(in *core.TidbBackupStatusStrategy, out *TidbBackupStatusStrategy, s conversion.Scope) error {
	return autoConvert_core_TidbBackupStatusStrategy_To_v1alpha1_TidbBackupStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_TidbBackupStrategy_To_core_TidbBackupStrategy(in *TidbBackupStrategy, out *core.TidbBackupStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_TidbBackupStrategy_To_core_TidbBackupStrategy is an autogenerated conversion function.
func Convert_v1alpha1_TidbBackupStrategy_To_core_TidbBackupStrategy(in *TidbBackupStrategy, out *core.TidbBackupStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbBackupStrategy_To_core_TidbBackupStrategy(in, out, s)
}

func autoConvert_core_TidbBackupStrategy_To_v1alpha1_TidbBackupStrategy(in *core.TidbBackupStrategy, out *TidbBackupStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_core_TidbBackupStrategy_To_v1alpha1_TidbBackupStrategy is an autogenerated conversion function.
func Convert_core_TidbBackupStrategy_To_v1alpha1_TidbBackupStrategy(in *core.TidbBackupStrategy, out *TidbBackupStrategy, s conversion.Scope) error {
	return autoConvert_core_TidbBackupStrategy_To_v1alpha1_TidbBackupStrategy(in, out, s)
}

func autoConvert_v1alpha1_TidbInstance_To_core_TidbInstance(in *TidbInstance, out *core.TidbInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TidbInstanceSpec_To_core_TidbInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TidbInstanceStatus_To_core_TidbInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TidbInstance_To_core_TidbInstance is an autogenerated conversion function.
func Convert_v1alpha1_TidbInstance_To_core_TidbInstance(in *TidbInstance, out *core.TidbInstance, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbInstance_To_core_TidbInstance(in, out, s)
}

func autoConvert_core_TidbInstance_To_v1alpha1_TidbInstance(in *core.TidbInstance, out *TidbInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_TidbInstanceSpec_To_v1alpha1_TidbInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_TidbInstanceStatus_To_v1alpha1_TidbInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_TidbInstance_To_v1alpha1_TidbInstance is an autogenerated conversion function.
func Convert_core_TidbInstance_To_v1alpha1_TidbInstance(in *core.TidbInstance, out *TidbInstance, s conversion.Scope) error {
	return autoConvert_core_TidbInstance_To_v1alpha1_TidbInstance(in, out, s)
}

func autoConvert_v1alpha1_TidbInstanceList_To_core_TidbInstanceList(in *TidbInstanceList, out *core.TidbInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.TidbInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_TidbInstanceList_To_core_TidbInstanceList is an autogenerated conversion function.
func Convert_v1alpha1_TidbInstanceList_To_core_TidbInstanceList(in *TidbInstanceList, out *core.TidbInstanceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbInstanceList_To_core_TidbInstanceList(in, out, s)
}

func autoConvert_core_TidbInstanceList_To_v1alpha1_TidbInstanceList(in *core.TidbInstanceList, out *TidbInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]TidbInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_TidbInstanceList_To_v1alpha1_TidbInstanceList is an autogenerated conversion function.
func Convert_core_TidbInstanceList_To_v1alpha1_TidbInstanceList(in *core.TidbInstanceList, out *TidbInstanceList, s conversion.Scope) error {
	return autoConvert_core_TidbInstanceList_To_v1alpha1_TidbInstanceList(in, out, s)
}

func autoConvert_v1alpha1_TidbInstanceSpec_To_core_TidbInstanceSpec(in *TidbInstanceSpec, out *core.TidbInstanceSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_PdSpec_To_core_PdSpec(&in.Pd, &out.Pd, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TikvSpec_To_core_TikvSpec(&in.Tikv, &out.Tikv, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TidbSpec_To_core_TidbSpec(&in.Tidb, &out.Tidb, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TidbInstanceSpec_To_core_TidbInstanceSpec is an autogenerated conversion function.
func Convert_v1alpha1_TidbInstanceSpec_To_core_TidbInstanceSpec(in *TidbInstanceSpec, out *core.TidbInstanceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbInstanceSpec_To_core_TidbInstanceSpec(in, out, s)
}

func autoConvert_core_TidbInstanceSpec_To_v1alpha1_TidbInstanceSpec(in *core.TidbInstanceSpec, out *TidbInstanceSpec, s conversion.Scope) error {
	if err := Convert_core_PdSpec_To_v1alpha1_PdSpec(&in.Pd, &out.Pd, s); err != nil {
		return err
	}
	if err := Convert_core_TikvSpec_To_v1alpha1_TikvSpec(&in.Tikv, &out.Tikv, s); err != nil {
		return err
	}
	if err := Convert_core_TidbSpec_To_v1alpha1_TidbSpec(&in.Tidb, &out.Tidb, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_TidbInstanceSpec_To_v1alpha1_TidbInstanceSpec is an autogenerated conversion function.
func Convert_core_TidbInstanceSpec_To_v1alpha1_TidbInstanceSpec(in *core.TidbInstanceSpec, out *TidbInstanceSpec, s conversion.Scope) error {
	return autoConvert_core_TidbInstanceSpec_To_v1alpha1_TidbInstanceSpec(in, out, s)
}

func autoConvert_v1alpha1_TidbInstanceStatus_To_core_TidbInstanceStatus(in *TidbInstanceStatus, out *core.TidbInstanceStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_TidbInstanceStatus_To_core_TidbInstanceStatus is an autogenerated conversion function.
func Convert_v1alpha1_TidbInstanceStatus_To_core_TidbInstanceStatus(in *TidbInstanceStatus, out *core.TidbInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbInstanceStatus_To_core_TidbInstanceStatus(in, out, s)
}

func autoConvert_core_TidbInstanceStatus_To_v1alpha1_TidbInstanceStatus(in *core.TidbInstanceStatus, out *TidbInstanceStatus, s conversion.Scope) error {
	return nil
}

// Convert_core_TidbInstanceStatus_To_v1alpha1_TidbInstanceStatus is an autogenerated conversion function.
func Convert_core_TidbInstanceStatus_To_v1alpha1_TidbInstanceStatus(in *core.TidbInstanceStatus, out *TidbInstanceStatus, s conversion.Scope) error {
	return autoConvert_core_TidbInstanceStatus_To_v1alpha1_TidbInstanceStatus(in, out, s)
}

func autoConvert_v1alpha1_TidbInstanceStatusStrategy_To_core_TidbInstanceStatusStrategy(in *TidbInstanceStatusStrategy, out *core.TidbInstanceStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_TidbInstanceStatusStrategy_To_core_TidbInstanceStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_TidbInstanceStatusStrategy_To_core_TidbInstanceStatusStrategy(in *TidbInstanceStatusStrategy, out *core.TidbInstanceStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbInstanceStatusStrategy_To_core_TidbInstanceStatusStrategy(in, out, s)
}

func autoConvert_core_TidbInstanceStatusStrategy_To_v1alpha1_TidbInstanceStatusStrategy(in *core.TidbInstanceStatusStrategy, out *TidbInstanceStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_core_TidbInstanceStatusStrategy_To_v1alpha1_TidbInstanceStatusStrategy is an autogenerated conversion function.
func Convert_core_TidbInstanceStatusStrategy_To_v1alpha1_TidbInstanceStatusStrategy(in *core.TidbInstanceStatusStrategy, out *TidbInstanceStatusStrategy, s conversion.Scope) error {
	return autoConvert_core_TidbInstanceStatusStrategy_To_v1alpha1_TidbInstanceStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_TidbInstanceStrategy_To_core_TidbInstanceStrategy(in *TidbInstanceStrategy, out *core.TidbInstanceStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_TidbInstanceStrategy_To_core_TidbInstanceStrategy is an autogenerated conversion function.
func Convert_v1alpha1_TidbInstanceStrategy_To_core_TidbInstanceStrategy(in *TidbInstanceStrategy, out *core.TidbInstanceStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbInstanceStrategy_To_core_TidbInstanceStrategy(in, out, s)
}

func autoConvert_core_TidbInstanceStrategy_To_v1alpha1_TidbInstanceStrategy(in *core.TidbInstanceStrategy, out *TidbInstanceStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_core_TidbInstanceStrategy_To_v1alpha1_TidbInstanceStrategy is an autogenerated conversion function.
func Convert_core_TidbInstanceStrategy_To_v1alpha1_TidbInstanceStrategy(in *core.TidbInstanceStrategy, out *TidbInstanceStrategy, s conversion.Scope) error {
	return autoConvert_core_TidbInstanceStrategy_To_v1alpha1_TidbInstanceStrategy(in, out, s)
}

func autoConvert_v1alpha1_TidbSpec_To_core_TidbSpec(in *TidbSpec, out *core.TidbSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Image = in.Image
	out.ImagePullPolicy = (*v1.PullPolicy)(unsafe.Pointer(in.ImagePullPolicy))
	out.Resources = in.Resources
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_v1alpha1_TidbSpec_To_core_TidbSpec is an autogenerated conversion function.
func Convert_v1alpha1_TidbSpec_To_core_TidbSpec(in *TidbSpec, out *core.TidbSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TidbSpec_To_core_TidbSpec(in, out, s)
}

func autoConvert_core_TidbSpec_To_v1alpha1_TidbSpec(in *core.TidbSpec, out *TidbSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Image = in.Image
	out.ImagePullPolicy = (*v1.PullPolicy)(unsafe.Pointer(in.ImagePullPolicy))
	out.Resources = in.Resources
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_core_TidbSpec_To_v1alpha1_TidbSpec is an autogenerated conversion function.
func Convert_core_TidbSpec_To_v1alpha1_TidbSpec(in *core.TidbSpec, out *TidbSpec, s conversion.Scope) error {
	return autoConvert_core_TidbSpec_To_v1alpha1_TidbSpec(in, out, s)
}

func autoConvert_v1alpha1_TikvSpec_To_core_TikvSpec(in *TikvSpec, out *core.TikvSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Image = in.Image
	out.ImagePullPolicy = (*v1.PullPolicy)(unsafe.Pointer(in.ImagePullPolicy))
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	out.Resources = in.Resources
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_v1alpha1_TikvSpec_To_core_TikvSpec is an autogenerated conversion function.
func Convert_v1alpha1_TikvSpec_To_core_TikvSpec(in *TikvSpec, out *core.TikvSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TikvSpec_To_core_TikvSpec(in, out, s)
}

func autoConvert_core_TikvSpec_To_v1alpha1_TikvSpec(in *core.TikvSpec, out *TikvSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Image = in.Image
	out.ImagePullPolicy = (*v1.PullPolicy)(unsafe.Pointer(in.ImagePullPolicy))
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	out.Resources = in.Resources
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_core_TikvSpec_To_v1alpha1_TikvSpec is an autogenerated conversion function.
func Convert_core_TikvSpec_To_v1alpha1_TikvSpec(in *core.TikvSpec, out *TikvSpec, s conversion.Scope) error {
	return autoConvert_core_TikvSpec_To_v1alpha1_TikvSpec(in, out, s)
}
