/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/pingcap/apiserver/pkg/apis/core/v1alpha1"
	scheme "github.com/pingcap/apiserver/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TidbBackupsGetter has a method to return a TidbBackupInterface.
// A group's client should implement this interface.
type TidbBackupsGetter interface {
	TidbBackups(namespace string) TidbBackupInterface
}

// TidbBackupInterface has methods to work with TidbBackup resources.
type TidbBackupInterface interface {
	Create(*v1alpha1.TidbBackup) (*v1alpha1.TidbBackup, error)
	Update(*v1alpha1.TidbBackup) (*v1alpha1.TidbBackup, error)
	UpdateStatus(*v1alpha1.TidbBackup) (*v1alpha1.TidbBackup, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.TidbBackup, error)
	List(opts v1.ListOptions) (*v1alpha1.TidbBackupList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TidbBackup, err error)
	TidbBackupExpansion
}

// tidbBackups implements TidbBackupInterface
type tidbBackups struct {
	client rest.Interface
	ns     string
}

// newTidbBackups returns a TidbBackups
func newTidbBackups(c *CoreV1alpha1Client, namespace string) *tidbBackups {
	return &tidbBackups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tidbBackup, and returns the corresponding tidbBackup object, and an error if there is any.
func (c *tidbBackups) Get(name string, options v1.GetOptions) (result *v1alpha1.TidbBackup, err error) {
	result = &v1alpha1.TidbBackup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tidbbackups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TidbBackups that match those selectors.
func (c *tidbBackups) List(opts v1.ListOptions) (result *v1alpha1.TidbBackupList, err error) {
	result = &v1alpha1.TidbBackupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tidbbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tidbBackups.
func (c *tidbBackups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tidbbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a tidbBackup and creates it.  Returns the server's representation of the tidbBackup, and an error, if there is any.
func (c *tidbBackups) Create(tidbBackup *v1alpha1.TidbBackup) (result *v1alpha1.TidbBackup, err error) {
	result = &v1alpha1.TidbBackup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tidbbackups").
		Body(tidbBackup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tidbBackup and updates it. Returns the server's representation of the tidbBackup, and an error, if there is any.
func (c *tidbBackups) Update(tidbBackup *v1alpha1.TidbBackup) (result *v1alpha1.TidbBackup, err error) {
	result = &v1alpha1.TidbBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tidbbackups").
		Name(tidbBackup.Name).
		Body(tidbBackup).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *tidbBackups) UpdateStatus(tidbBackup *v1alpha1.TidbBackup) (result *v1alpha1.TidbBackup, err error) {
	result = &v1alpha1.TidbBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tidbbackups").
		Name(tidbBackup.Name).
		SubResource("status").
		Body(tidbBackup).
		Do().
		Into(result)
	return
}

// Delete takes name of the tidbBackup and deletes it. Returns an error if one occurs.
func (c *tidbBackups) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tidbbackups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tidbBackups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tidbbackups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tidbBackup.
func (c *tidbBackups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TidbBackup, err error) {
	result = &v1alpha1.TidbBackup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tidbbackups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
